name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Python script
        run: python main.py

      - name: Zip code and model
        run: zip -r my_code_and_model.zip . -x ./.git/**\*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my_code_and_model
          path: my_code_and_model.zip 
